/* Automatically generated by './build/bin/build-entry.js' */

import Padding from '../packages/padding/index.js';
import Margin from '../packages/margin/index.js';
import FlexBox from '../packages/flex-box/index.js';
import Title from '../packages/title/index.js';
import TagColor from '../packages/tag-color/index.js';
import ScrollDiv from '../packages/scroll-div/index.js';
import BaseTable from '../packages/base-table/index.js';
import TableColumn from '../packages/table-column/index.js';
import Tooltip from '../packages/tooltip/index.js';
import Pagination from '../packages/pagination/index.js';
import Input from '../packages/input/index.js';
import Dialog from '../packages/dialog/index.js';
import Dropdown from '../packages/dropdown/index.js';

const components = [
  Padding,
  Margin,
  FlexBox,
  Title,
  TagColor,
  ScrollDiv,
  BaseTable,
  TableColumn,
  Tooltip,
  Pagination,
  Input,
  Dialog,
  Dropdown
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.3',
  install,
  Padding,
  Margin,
  FlexBox,
  Title,
  TagColor,
  ScrollDiv,
  BaseTable,
  TableColumn,
  Tooltip,
  Pagination,
  Input,
  Dialog,
  Dropdown
};
